PUT https://api.aws-handson.com/cards/groups/x001/words/plague HTTP/1.1

{
  "correct": true,
  "times": 0
}


PUT http://127.0.0.1:3000/groups/x001/words/plague HTTP/1.1

{
  "correct": true,
  "times": 0
}