# OPTIONS https://api.aws-handson.com/cards/groups/x001/words/republic

# Access-Control-Request-Headers: content-type
# Access-Control-Request-Method: PUT
POST https://hooks.slack.com/services/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

{"text": "{とても重要なことが起こりました！詳しくは、<https://alert-system.com/alerts/1234|ここをクリック>してください！"}

POST https://translation.googleapis.com/language/translate/v2?key=AIzaSyBMfljB2mqLVpuWZhi2m5VI6R_9zZERXEk

{
  "q": "track",
  "from": "en",
  "target": "ja",
  "format": "text"
}

GET https://api.aws-handson.com/groups/x001/new
Accept: application/json, text/plain, */*
Authorization: eyJraWQiOiI1UTliTGh4akdYT2dBV285ZVBraHRFUEU3UGxjK0w0UGRSZEY5Snl5TGFZPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJmOTUxNDU3ZC02Njk0LTRiZjgtYWY4ZC0xZmJjMDI3MTBlY2EiLCJhdWQiOiIyMWRicjQ2dmZwdWFqNG1wbWxtYmlnb3F1YiIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJldmVudF9pZCI6ImQyOTMzOGMwLTNiMTAtNDVhOC05MmZmLWM4Yjc5OGMyZmRhYyIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNTcxMDE3Nzg2LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuYXAtbm9ydGhlYXN0LTEuYW1hem9uYXdzLmNvbVwvYXAtbm9ydGhlYXN0LTFfanFKdkUxcWRIIiwiY29nbml0bzp1c2VybmFtZSI6Ind3YWxwaGEiLCJleHAiOjE1NzEwMjEzODYsImlhdCI6MTU3MTAxNzc4NiwiZW1haWwiOiJ3d2FscGhhQGdtYWlsLmNvbSJ9.qsuPa0R5HnpnP32zzgcjQcAIBWwFHCFfDZVvlElDARkGj38GUnI6z-20CmWZ25GTrSwin0_oEdWkTOVs0EpgwheBgRLdXF9mmcshd04TR29jWO2pU0eFvpPIYGYJhctw7_hSUgdcOfWzrEc5btmfJA2s6r86-2RFLGwaKcFgaHLm-NuvSoV8ahCggA2wz2hlPsn4wn-G9_GhRi3yzu9Milc0E7Mi5NCOZNWvboqldpHmMbLi62bsEoLgWem-DoTgBuVPNjonJJSK4mrOF8cDYy1VZoYhbw8kJNdt4CHTduN4Jmi2rr7ugNDCYmJt159emYnHYH835ELKWhxDqiXmJQ
Origin: https://localhost
Referer: https://localhost/home/study/card
Sec-Fetch-Mode: cors
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

GET https://api.dev.aws-handson.com/history
Accept: application/json, text/plain, */*
Authorization: eyJraWQiOiJTaWlEVjhENWg2MWw0ZktjXC9UOXR2SFI1ZDQwbDZMMWkwRW9BOENtaklaRT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjYmZmMzcxYy1lZjk3LTRhZmMtYjZhMy0xNjZjMjE2MzMwN2UiLCJhdWQiOiJyZWxtODc0YzZoa2pvdXFhbHZ2cTB1dHRoIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNTcxMDMyNjEyLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuYXAtbm9ydGhlYXN0LTEuYW1hem9uYXdzLmNvbVwvYXAtbm9ydGhlYXN0LTFfUG40cHdCaVkwIiwiY29nbml0bzp1c2VybmFtZSI6Ind3YWxwaGEiLCJleHAiOjE1NzEwMzYyMTIsImlhdCI6MTU3MTAzMjYxMiwiZW1haWwiOiJ3d2FscGhhQGdtYWlsLmNvbSJ9.BYf_WzeedAD8cUhMRk8ZdwPVAuitETlDVuHqV2LGvL9KINKHHA87cTJq2n2P-HziBeetBiksYmOmAcWA-qqqgHE5EKLQMLsfkP1aVEiZQw2CcENIoCnewUGTdsK36KF_fGgLKKqeegJN3F_nXwL4kxics3IQ7msst0dc04pZUy0xnCg48n6ubtRzjBWRgqpybNM_T1tu8UMdtwiwk2GgqNe-IkUnSH2m1L8eMpxSEXBTQemLJmTbdDCx_e-_XSiraWTiKMiu23_q9bUj2aYAxTMu1PdqQYvNUHYxL3d8BLuSTxVYYE-q2mvdZEUl-jXifualX4qiPEn_FQ4g0-2d3Q
Origin: https://cards.dev.aws-handson.com
Referer: https://cards.dev.aws-handson.com/mypage
Sec-Fetch-Mode: cors
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

GET http://127.0.0.1:3000/groups
Accept: application/json, text/plain, */*
Authorization: eyJraWQiOiI1UTliTGh4akdYT2dBV285ZVBraHRFUEU3UGxjK0w0UGRSZEY5Snl5TGFZPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJmOTUxNDU3ZC02Njk0LTRiZjgtYWY4ZC0xZmJjMDI3MTBlY2EiLCJhdWQiOiIyMWRicjQ2dmZwdWFqNG1wbWxtYmlnb3F1YiIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJldmVudF9pZCI6ImQyOTMzOGMwLTNiMTAtNDVhOC05MmZmLWM4Yjc5OGMyZmRhYyIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNTcxMDE3Nzg2LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuYXAtbm9ydGhlYXN0LTEuYW1hem9uYXdzLmNvbVwvYXAtbm9ydGhlYXN0LTFfanFKdkUxcWRIIiwiY29nbml0bzp1c2VybmFtZSI6Ind3YWxwaGEiLCJleHAiOjE1NzEwMjEzODYsImlhdCI6MTU3MTAxNzc4NiwiZW1haWwiOiJ3d2FscGhhQGdtYWlsLmNvbSJ9.qsuPa0R5HnpnP32zzgcjQcAIBWwFHCFfDZVvlElDARkGj38GUnI6z-20CmWZ25GTrSwin0_oEdWkTOVs0EpgwheBgRLdXF9mmcshd04TR29jWO2pU0eFvpPIYGYJhctw7_hSUgdcOfWzrEc5btmfJA2s6r86-2RFLGwaKcFgaHLm-NuvSoV8ahCggA2wz2hlPsn4wn-G9_GhRi3yzu9Milc0E7Mi5NCOZNWvboqldpHmMbLi62bsEoLgWem-DoTgBuVPNjonJJSK4mrOF8cDYy1VZoYhbw8kJNdt4CHTduN4Jmi2rr7ugNDCYmJt159emYnHYH835ELKWhxDqiXmJQ

GET http://localhost:3000/groups/x001/new


GET http://127.0.0.1:3000/